spring:
  datasource:
    url: jdbc:mysql://testdb.chmcecui04ju.ap-northeast-2.rds.amazonaws.com:3306/healeat
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000